apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: credit-api
  description: Retrieve credit details
spec:
  type: openapi
  lifecycle: development
  owner: credit-squad
  system: credit
  definition: |
    openapi: "1.0.0"
    info:
      version: 1.0.0
      title: Credit API
      license:
        name: private
    servers:
      - url: http://cpwapp03a-rj.modal.net.br
    paths:
      /list:
        get:
          summary: List all credits
